File/2-build-application-framework-aspdotnet-mvc-5-m2-exercise-files/After/FailTracker.Web/Models/Issue/IssueDetailsViewModel.cs
using System;

namespace FailTracker.Web.Models.Issue
{
	public class IssueDetailsViewModel
	{
		public int IssueID { get; set; }
		public string Subject { get; set; }
		public DateTime CreatedAt { get; set; }
		public string Body { get; set; }
	}
}

File/2-build-application-framework-aspdotnet-mvc-5-m2-exercise-files/After/FailTracker.Web/Models/Issue/IssueSummaryViewModel.cs
using System;

namespace FailTracker.Web.Models.Issue
{
	public class IssueSummaryViewModel
	{
		public int IssueID { get; set; }
		public string Subject { get; set; }
		public DateTime CreatedAt { get; set; }
	}
}

File/2-build-application-framework-aspdotnet-mvc-5-m2-exercise-files/After/FailTracker.Web/Models/Issue/NewIssueForm.cs
namespace FailTracker.Web.Models.Issue
{
	public class NewIssueForm
	{
		public string Subject { get; set; }
		public string Body { get; set; }
	}
}

File/2-build-application-framework-aspdotnet-mvc-5-m2-exercise-files/After/FailTracker.Web/Controllers/IssueController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using FailTracker.Web.Data;
using FailTracker.Web.Domain;
using FailTracker.Web.Filters;
using FailTracker.Web.Infrastructure;
using FailTracker.Web.Models.Issue;
using Microsoft.AspNet.Identity;

namespace FailTracker.Web.Controllers
{
	public class IssueController : Controller
	{
		private readonly ApplicationDbContext _context;
		private readonly ICurrentUser _currentUser;

		public IssueController(ApplicationDbContext context, 
			ICurrentUser currentUser)
		{
			_context = context;
			_currentUser = currentUser;
		}

		[ChildActionOnly]
		public ActionResult IssueWidget()
		{
			var models = from i in _context.Issues
				select new IssueSummaryViewModel
				{
					IssueID = i.IssueID,
					Subject = i.Subject,
					CreatedAt = i.CreatedAt
				};

			return PartialView(models.ToArray());
		}

		public ActionResult New()
		{
			return View();
		}

		[HttpPost, ValidateAntiForgeryToken, Log("Created issue")]
		public ActionResult New(NewIssueForm form)
		{
			_context.Issues.Add(new Issue(_currentUser.User, form.Subject, form.Body));

			_context.SaveChanges();

			return RedirectToAction("Index", "Home");
		}

		[Log("Viewed issue {id}")]
		public ActionResult View(int id)
		{
			var issue = _context.Issues.Find(id);

			if (issue == null)
			{
				throw new ApplicationException("Issue not found!");
			}
			
			return View(new IssueDetailsViewModel
			{
				IssueID = issue.IssueID,
				Subject = issue.Subject,
				CreatedAt = issue.CreatedAt,
				Body = issue.Body
			});
		}

		[HttpPost, ValidateAntiForgeryToken, Log("Deleted issue {id}")]
		public ActionResult Delete(int id)
		{
			var issue = _context.Issues.Find(id);

			if (issue == null)
			{
				throw new ApplicationException("Issue not found!");
			}

			_context.Issues.Remove(issue);

			_context.SaveChanges();
			
			return RedirectToAction("Index", "Home");
		}
	}
}

File/2-build-application-framework-aspdotnet-mvc-5-m2-exercise-files/After/FailTracker.Web/Views/Issue/IssueWidget.cshtml
@model FailTracker.Web.Models.Issue.IssueSummaryViewModel[]
@{
    //Layout = null;
}
<table class="table table-hover">
    <thead>
        <tr>
            <th>Subject</th>
            <th>Created At</th>
        </tr>
    </thead>
    <tbody class="row-link" data-link="row">
        @foreach (var issue in Model)
        {
            <tr>
                <td>@Html.ActionLink(@issue.Subject, "View", "Issue", routeValues:new{id=@issue.IssueID}, htmlAttributes:null)</td>
                <td>@issue.CreatedAt.ToShortDateString()</td>
            </tr>   
        }
    </tbody>
</table>

File/2-build-application-framework-aspdotnet-mvc-5-m2-exercise-files/After/FailTracker.Web/Views/Issue/New.cshtml
@model FailTracker.Web.Models.Issue.NewIssueForm

@{
    ViewBag.Title = "New Issue";
}

<h2>New Issue</h2>
@using (Html.BeginForm("New", "Issue", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <div class="form-group">
        @Html.LabelFor(m => m.Subject, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Subject, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Subject)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Body, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextAreaFor(m => m.Body, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Body)
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Add Issue" class="btn btn-default" />
        </div>
    </div>
}

File/2-build-application-framework-aspdotnet-mvc-5-m2-exercise-files/After/FailTracker.Web/Views/Issue/View.cshtml
@model FailTracker.Web.Models.Issue.IssueDetailsViewModel

@{
    ViewBag.Title = Model.Subject;
}

<h2>
    @Model.Subject
    <span class="pull-right">Received @Model.CreatedAt</span>
</h2>
<div class="well">
    <p class="lead">
        @Model.Body
    </p>
    <div>
        @using (Html.BeginForm("Delete", "Issue", new {id = Model.IssueID}, FormMethod.Post, new{id="delete-form"}))
        {
            @Html.AntiForgeryToken()
            <button type="submit" class="btn btn-warning">Delete Issue</button>
        }
    </div>
</div>

@section scripts
{
    <script>
        $(function() {
            $("#delete-form").on("submit", function () {
                return confirm("Are you sure you wish to delete this issue?  You cannot undo this action.");
            });
        });
    </script>
}